name: chirpy 
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=4.9.*
  - ipython=6.5.*
  - jupyter=1.0.*
  - jupyter_core=4.4.*
  - matplotlib=3.1.*
  - numpy=1.16.*
  - packmol=18.169
  - pip==19.1.*
  - python=3.7.*
  - scipy=1.3.*
  - pip:
    - mayavi==4.7.*
    - pyqt5==5.13.*
    - pytest==5.1.*

