name: chirpy 
channels:
  - conda-forge
  - defaults
dependencies:
  - fortranformat=0.2.5
  - ipython=7.16.*
  - jupyter=1.0.*
  - jupyter_core=4.6.*
  - matplotlib=3.3.*
  - mdanalysis=1.0.* 
  - numpy=1.19.*
  - packmol=18.169
  - periodictable=1.5.*
  - pip=20.1.*
  - pycifrw=4.4.*
  - python=3.8.*
  - scipy=1.5.*
      - pip:
    - concurrent-iterator==0.2.*
    - pyqt5==5.15.*

