name: chirpy 
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.2.*
  - ipython=7.13.*
  - jupyter=1.0.*
  - jupyter_core=4.6.*
  - matplotlib=3.2.*
  - numpy=1.18.*
  - packmol=18.169
  - pip=20.0.*
  - python=3.7.*
  - scipy=1.4.*
  - mdanalysis=0.19.* 
  - pycifrw=4.4.*
  - pip:
    - mayavi==4.7.*
    - pyqt5==5.13.*

